# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-22 09:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=b'alergenos/')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message=b"El telefono debe tener el formato: '+999999999'. Maximo 15 digitos.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facultad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.IntegerField(choices=[(0, b'Inactivo'), (1, b'Activo')], default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=b'categoria/')),
                ('cafeteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bos.Cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_empleado', models.IntegerField(choices=[(1, b'Encargado'), (2, b'Camarero')], default=2)),
                ('cafeteria', models.ManyToManyField(blank=True, to='bos.Cafeteria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=b'etiquetas/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.IntegerField(choices=[(0, b'Inactivo'), (1, b'Activo')], default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=b'menu/')),
                ('precio', models.FloatField(blank=True, null=True)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('cafeteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bos.Cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='MenuPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_menu', models.FloatField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('descuento_porcentual', models.IntegerField(blank=True, null=True)),
                ('descuento_numerico', models.FloatField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=b'oferta/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(choices=[(0, b'Inactivo'), (1, b'Activo')], default=0)),
                ('valido_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('precio_oferta', models.FloatField(blank=True, null=True)),
                ('cafeteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bos.Cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_oferta', models.FloatField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Oferta')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_oferta', models.FloatField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Oferta')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', django_fsm.FSMField(choices=[(b'En cola', b'En cola'), (b'En proceso', b'En proceso'), (b'Preparado', b'Preparado'), (b'Entregado', b'Entregado'), (b'No recogido', b'No recogido'), (b'Cancelado', b'Cancelado')], default=(b'En cola', b'En cola'), max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('recogida_estimada', models.DateTimeField()),
                ('fecha_recogida', models.DateTimeField(blank=True, null=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to=b'qr/')),
                ('importe', models.FloatField(blank=True, null=True)),
                ('codigo_confirmacion', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('observaciones', models.CharField(blank=True, max_length=60, null=True)),
                ('cafeteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bos.Cafeteria')),
                ('menus', models.ManyToManyField(through='bos.MenuPedido', to='bos.Menu')),
                ('ofertas', models.ManyToManyField(through='bos.OfertaPedido', to='bos.Oferta')),
                ('ordenante', models.ManyToManyField(related_name='alumnos', to='bos.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('calorias', models.FloatField(blank=True, null=True)),
                ('grasas_saturadas', models.FloatField(blank=True, null=True)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=b'productos/')),
                ('precio_oferta', models.FloatField(blank=True, default=0.0, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(choices=[(0, b'Inactivo'), (1, b'Activo')], default=0)),
                ('alergenos', models.ManyToManyField(blank=True, to='bos.Alergeno')),
                ('cafeteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bos.Cafeteria')),
                ('etiquetas', models.ManyToManyField(blank=True, to='bos.Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('precio_producto', models.FloatField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=400, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Alumno')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='bos.ProductoPedido', to='bos.Producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='resenas',
            field=models.ManyToManyField(blank=True, to='bos.Resena'),
        ),
        migrations.AddField(
            model_name='ofertaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Producto'),
        ),
        migrations.AddField(
            model_name='ofertapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Pedido'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='productos',
            field=models.ManyToManyField(through='bos.OfertaProducto', to='bos.Producto'),
        ),
        migrations.AddField(
            model_name='menuproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Producto'),
        ),
        migrations.AddField(
            model_name='menupedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Pedido'),
        ),
        migrations.AddField(
            model_name='menu',
            name='productos',
            field=models.ManyToManyField(through='bos.MenuProducto', to='bos.Producto'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='productos',
            field=models.ManyToManyField(to='bos.Producto'),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Universidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cafeteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Cafeteria'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Universidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
