# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-07 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(null=True, upload_to=b'alergenos/')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facultad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Cafeteria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(null=True, upload_to=b'etiquetas/')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('descuento_porcentual', models.IntegerField(blank=True, null=True)),
                ('descuento_numerico', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[(b'EC', b'En cola'), (b'EP', b'En proceso'), (b'P', b'Preparado'), (b'E', b'Entregado'), (b'NR', b'No recogido'), (b'C', b'Cancelado')], default=b'EC', max_length=2)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('recogida_estimada', models.DateField()),
                ('fecha_recogida', models.DateField(blank=True, null=True)),
                ('qr', models.ImageField(null=True, upload_to=b'qr/')),
                ('alumnos', models.ManyToManyField(related_name='alumnos', to='bos.Alumno')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Alumno')),
                ('menus', models.ManyToManyField(null=True, related_name='menus', to='bos.Menu')),
                ('ofertas', models.ManyToManyField(related_name='ofertas', to='bos.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('calorias', models.FloatField(blank=True, null=True)),
                ('grasas_saturadas', models.FloatField(blank=True, null=True)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=b'productos/')),
                ('alergenos', models.ManyToManyField(blank=True, null=True, to='bos.Alergeno')),
                ('etiquetas', models.ManyToManyField(blank=True, null=True, to='bos.Etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=400, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='bos.Producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='resenas',
            field=models.ManyToManyField(to='bos.Resena'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='productos',
            field=models.ManyToManyField(to='bos.Producto'),
        ),
        migrations.AddField(
            model_name='menu',
            name='productos',
            field=models.ManyToManyField(to='bos.Producto'),
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Universidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cafeteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Cafeteria'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bos.Universidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
